// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back.data;

#nullable disable

namespace back.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230516231424_added DevPriorities, DevStatus, Games, GameEngine, Genre, Platform entities")]
    partial class addedDevPrioritiesDevStatusGamesGameEngineGenrePlatformentities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("back.Models.DevPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DevPriorities");
                });

            modelBuilder.Entity("back.Models.DevStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DevStatuses");
                });

            modelBuilder.Entity("back.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("Budget")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DevPriorityId")
                        .HasColumnType("int");

                    b.Property<int?>("DevStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EstimatedReleaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GameEngineId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayer")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayer")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UsersScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DevPriorityId");

                    b.HasIndex("DevStatusId");

                    b.HasIndex("GameEngineId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("back.Models.GameEngine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("GameEngines");
                });

            modelBuilder.Entity("back.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("back.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("newses");
                });

            modelBuilder.Entity("back.Models.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("back.Models.Game", b =>
                {
                    b.HasOne("back.Models.DevPriority", "DevPriority")
                        .WithMany()
                        .HasForeignKey("DevPriorityId");

                    b.HasOne("back.Models.DevStatus", "DevStatus")
                        .WithMany()
                        .HasForeignKey("DevStatusId");

                    b.HasOne("back.Models.GameEngine", "GameEngine")
                        .WithMany()
                        .HasForeignKey("GameEngineId");

                    b.Navigation("DevPriority");

                    b.Navigation("DevStatus");

                    b.Navigation("GameEngine");
                });

            modelBuilder.Entity("back.Models.Genre", b =>
                {
                    b.HasOne("back.Models.Game", null)
                        .WithMany("Genre")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("back.Models.Platform", b =>
                {
                    b.HasOne("back.Models.Game", null)
                        .WithMany("Platform")
                        .HasForeignKey("GameId");
                });

            modelBuilder.Entity("back.Models.Game", b =>
                {
                    b.Navigation("Genre");

                    b.Navigation("Platform");
                });
#pragma warning restore 612, 618
        }
    }
}
